#!/bin/bash
# Deployment Commands for ARIS API Fixes
# Run these commands to deploy your latest code

echo "=============================================="
echo "DEPLOYMENT COMMANDS"
echo "=============================================="
echo ""
echo "Copy and paste these commands to deploy:"
echo ""
echo "# 1. Copy deployment package to server"
echo "scp /home/senarios/Desktop/aris/aris_final_deployment.tar.gz ubuntu@44.221.84.58:/tmp/"
echo ""
echo "# 2. SSH into server and deploy"
echo "ssh ubuntu@44.221.84.58"
echo ""
echo "# 3. Once connected, run these commands:"
echo "cd /tmp"
echo "tar -xzf aris_final_deployment.tar.gz"
echo "sudo cp schemas.py main.py service.py /home/ubuntu/aris/api/"
echo "sudo systemctl restart aris-fastapi"
echo "echo '✅ Deployment complete!'"
echo "exit"
echo ""
echo "=============================================="
echo ""
echo "OR use this ONE-LINE command (if SSH is configured):"
echo ""
echo "scp /home/senarios/Desktop/aris/aris_final_deployment.tar.gz ubuntu@44.221.84.58:/tmp/ && ssh ubuntu@44.221.84.58 'cd /tmp && tar -xzf aris_final_deployment.tar.gz && sudo cp schemas.py main.py service.py /home/ubuntu/aris/api/ && sudo systemctl restart aris-fastapi && echo \"✅ Deployed!\"'"
echo ""
echo "=============================================="
